### ISSUE TITLE
Sort region names from A-Z

### ISSUE THREAD

**Issue by mduong7** [MapofLife/places#5]
Currently sorting Z-A

**Comment by funkycoda** [comment]
Updated as part of https://github.com/MapofLife/regions/commit/9122a8219e04480ed7cbb118e1b2d48e8474ae50

**Comment by johnWilshire** [comment]
Checked for
* [protected areas in Ecuador](https://mol.org/places/explore?region=Ecuador&regionid=820244c0-44c5-4fe3-81d3-f01556fde5c5&type=countries&bounds=-92.0089,-5.0174,-75.2,1.6815) 
* [provinces in Perú](https://mol.org/places/explore?region=Peru&regionid=d782caea-8e79-40f3-b938-47e3006b0766&type=countries&bounds=-81.3307,-18.3518,-68.6531,-0.0375)

**Comment by yanisica** [comment]
I checked all region in Colombia and it is working!
