### ISSUE TITLE
Disable 'actions' at the country level

### ISSUE THREAD

**Issue by mduong7** [MapofLife/places#6]
Confirm region_id in actions for a sub-region (not country).
From Yanina → In field guides and management plans here, I looked for the region_id of the 3 countries and did not find any.

**Comment by funkycoda** [comment]
Updated as part of https://github.com/MapofLife/regions/commit/395f956601bbb2dc41294dcd82e4d09532df615f

**Comment by johnWilshire** [comment]
Confirmed for Columbia, Ecuador and Peru.

**Comment by yanisica** [comment]
Actions are disabled at the country level.
