### ISSUE TITLE
Remove region type label

### ISSUE THREAD

**Issue by mduong7** [MapofLife/places#8]
Remove region type label (i.e., Indigenous territory), should only show when selecting from a list of region types (i.e., parks, gadm1, hydrosheds). @funkycoda to confirm if this is feasible.

**Comment by funkycoda** [comment]
Updated as part of https://github.com/MapofLife/regions/commit/395f956601bbb2dc41294dcd82e4d09532df615f

**Comment by johnWilshire** [comment]
I am not sure I understand the issue.

![Screen Shot 2019-11-27 at 4 05 20 PM](https://user-images.githubusercontent.com/1732458/69759400-08aed780-1130-11ea-953b-fe2ccc792930.png)

The only place the region type shows up on pages that I can see is here.

**Comment by mduong7** [comment]
Righto, I see why this doesn't make a ton of sense. This issue was created for Nigel, because he didn't want to show the 'Indigenous Territories' label. We decided to keep the label for everything, but hide Indigenous Territories for less downstream headaches for the regions module.

**Comment by yanisica** [comment]
Confirmed that indigenous territories label is hidden.

**Comment by mduong7** [comment]
I checked a indigenous regions for Peru and Colombia. The dataset label is hidden. Closing.
